### YamlMime:ManagedReference

apiRules:
- exclude:
    uidRegex: ^System\.Object\..*$
- exclude:
    uidRegex: ^System\.Windows\.Application(\..*)?$
- exclude:
    uidRegex: ^System\.Windows\.Controls.ContentControl(\..*)?$
- exclude:
    uidRegex: ^System\.Windows\.Controls\.Control(\..*)?$
- exclude:
    uidRegex: ^System\.Windows\.DependencyObject(\..*)?$
- exclude:
    uidRegex: ^System\.Windows\.FrameworkElement(\..*)?$
- exclude:
    uidRegex: ^System\.Windows\.FrameworkContentElement(\..*)?$
- exclude:
    uidRegex: ^System\.Windows\.Media.Visual(\..*)?$
- exclude:
    uidRegex: ^System\.Windows\.Threading.DispatcherObject(\..*)?$
- exclude:
    uidRegex: ^System\.Windows\.UIElement(\..*)?$
- exclude:
    uidRegex: ^System\.Windows\.Window(\..*)?$