<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWPF>true</UseWPF>
    <OutputType>Library</OutputType>
    <ImplicitUsings>enable</ImplicitUsings>
    <AssemblyName>$(MSBuildProjectName.ToLower())</AssemblyName>
    <AssemblyTitle>Pixel Magnification Control for WPF</AssemblyTitle>
    <PackageId>$(AssemblyName)</PackageId>
    <Company>Jad Altahan</Company>
    <Copyright>Copyright (C) 2025, Jad Altahan</Copyright>
    <FileVersion>1.0.0.0</FileVersion>
    <Version>1.0.0</Version>
    <IncludeSourceRevisionInInformationalVersion>false</IncludeSourceRevisionInInformationalVersion>
    <PackageReadmeFile>README.md</PackageReadmeFile>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
    <DebugType>portable</DebugType>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
    <DebugType>none</DebugType>
  </PropertyGroup>

  <ItemGroup>
    <None Include="..\README.md">
      <Pack>True</Pack>
      <PackagePath>\</PackagePath>
    </None>
  </ItemGroup>

  <ItemGroup>
    <Resource Include="Resources\Cursors\simple_inverted_cross.cur" />
    <Resource Include="Resources\Cursors\cross.cur" />
    <Resource Include="Resources\Sounds\ui_click.wav" />
    <Resource Include="Resources\Sounds\ui_notify.wav" />
    <Resource Include="Resources\Sounds\ui_pop.wav" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Windows.CsWin32" Version="0.3.205">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>
</Project>
